### ISSUE TITLE
Sync wp taxonomy field with CiviCRM contact field ?

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-acf-integration#4] opened 2020-06-16 16:39 UTC
Hi

I'm wondering if your insane module could be used to sync one type of CiviCRM contact type, namely organisation, of which we do have the details in Civi, to the Event Organiser Venue taxonomy ? 

This would avoid entering it twice, as soon as an organisation is added in Civi, it is available in event organiser as a venue !

:)

**Comment by danaskallman** [comment] 2020-06-16 17:40
Is there a relationship between a location of an event in CiviEvent and an organization? I don't think there is, how would that even work if there is no connectivity between them in CiviCRM itself?

**Comment by christianwach** [comment] 2020-06-16 17:46
@jbonlinea Part of the problem is that CiviCRM's UI for managing "CiviEvent Locations" is, shall we say, not very good. There's no list of CiviEvent Locations like there is a list of Venues in Event Organiser, for example. This makes it tricky to work with.

Second (as Dana just pointed out) not all Organisation Addresses are necessarily CiviEvent Locations. So an automatic sync of Organisation Addresses to CiviEvent Locations and then on to Event Organiser Venues wouldn't make sense to everyone. And given the problems with the UI for managing CiviEvent Locations, how would we mark *some* Organisation Addresses as CiviEvent Locations?

I'm happy to leave this issue open for further discussion of course - but it sounds to me that if your system is set up that way then you're looking at a custom plugin rather than extending this one.

**Comment by jbonlinea** [comment] 2020-06-22 17:50
Hi :)

Yeah, I don't know well enough how Civi internals are built in this respect but a thumb thinking would say, why would we need to have event-location at all ?
any contact addressed is an event location in civi...  if the event takes place in  public place like in the streets, make the contact the cityhall, and if it's far in the bush make the contact your best friend the lion king :)

Joke aside, can't we add a custom field to an organization address ? not to an organisation, but one of its address ? this would enable to define that this address is an event location ?
 
--- 
 
I wish this could be a workaround but i dont think so, and not sure worth implementing when there are not plenty of event locations ?

Build your WP organization CPT with pods, 
At the custom field you would like to sync with Civi in ACF
Sync your Civi organisation address to your CPT thank's to your module

Sync your organisation custom field to event-category taxonomy thank's to the first sniplet of pods [pods_api_post_save_pod_item_podname](https://pods.io/docs/code/action-reference/pods_api_post_save_pod_item_podname/) 

... well the fact is that event-category needs fields like "street, postcode,etc." while organisation adresse in the ACF field is a google map type...

Arf'

**Comment by christianwach** [comment] 2020-06-25 13:01
> can't we add a custom field to an organization address ? not to an organisation, but one of its address ? this would enable to define that this address is an event location ?

This may be possible, but I don't see it as part of this plugin. It might be better suited to CiviCRM Event Organiser, but sounds like a custom solution rather than a general one.

Also, please see [this note](https://github.com/christianwach/civicrm-acf-integration#address-field) in the Read Me. Addresses are *really* complicated, especially when you consider that they are differently formatted in different countries.

**Comment by christianwach** [comment] 2021-04-08 12:34
Closing because I am archiving this repo in favour of [CiviCRM Profile Sync](https://github.com/christianwach/civicrm-wp-profile-sync).

**Closed as completed by christianwach** 2021-04-08 12:34 UTC
